<a href="https://colab.research.google.com/github/clopezv/alura-challenge-14-04-2025/blob/main/CargarPaginaHTML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**Alura 4- Leyendo páginas HTMl y XML**
Importando páginas web

In [ ]:
import pandas as pd

In [7]:
datos_html = pd.read_html('/content/peliculas_wikipedia.html') #Muestra las tablas html
datos_html

<ipython-input-7-99c8cb29699b>:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  datos_html = pd.read_html('/content/peliculas_wikipedia.html') #Muestra las tablas html

ValueError: No tables found

In [ ]:
type(datos_html)

list

In [6]:
len(datos_html)

NameError: name 'datos_html' is not defined

In [8]:
top_peliculas = datos_html[1]
top_peliculas

NameError: name 'datos_html' is not defined

In [5]:
datos_html = pd.read_html('/content/peliculas_wikipedia.html')[1]#Muestra la segunda tabla
datos_html

<ipython-input-5-ef0074ba25bf>:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  datos_html = pd.read_html('/content/peliculas_wikipedia.html')[1]#Muestra la segunda tabla
/usr/local/lib/python3.11/dist-packages/pandas/io/html.py:661: MarkupResemblesLocatorWarning: The input passed in on this line looks more like a filename than HTML or XML.

If you meant to use Beautiful Soup to parse the contents of a file on disk, then something has gone wrong. You should open the file first, using code like this:

    filehandle = open(your filename)

You can then feed the open filehandle into Beautiful Soup instead of using the filename.

However, if you want to parse some data that happens to look like a filename, then nothing has gone wrong: you are using Beautiful Soup correctly, and this warning is spurious and can be filtered. To make this warning go away, run this code before calling the BeautifulSoup constructor:

    from bs4 import MarkupResemblesLocatorWarning
    import warnings

    warnings.filterwarnings("ignore", category=MarkupResemblesLocatorWarning)

  soup = BeautifulSoup(udoc, features="html5lib", from_encoding=from_encoding)

ValueError: No tables found

###**Escribiendo Archivos HTML**

In [ ]:
type(top_peliculas)

In [ ]:
top_peliculas.to_html('top_peliculas.html', index=False)

In [ ]:
pd.read_html('/content/top_peliculas.html')

[                            Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles
 1                     Casablanca          1942        Michael Curtiz
 2                  The Godfather          1972  Francis Ford Coppola
 3             Gone with the Wind          1939        Victor Fleming
 4             Lawrence of Arabia          1962            David Lean
 ..                           ...           ...                   ...
 95                 The Searchers          1956             John Ford
 96              Bringing Up Baby          1938          Howard Hawks
 97                    Unforgiven          1992        Clint Eastwood
 98  Guess Who's Coming to Dinner          1967        Stanley Kramer
 99           Yankee Doodle Dandy          1942        Michael Curtiz

                       Production companies  Rank
 0                       RKO Radio Pictures     1
 1                    Warner Bros. Pictures     2
 2   Paramount Pictures, Alfran Productions     3
 3          Selznick International Pictures     4
 4                         Horizon Pictures     5
 ..                                     ...   ...
 95                  C. V. Whitney Pictures    96
 96                      RKO Radio Pictures    97
 97                     The Malpaso Company    98
 98                       Columbia Pictures    99
 99                   Warner Bros. Pictures   100

 [100 rows x 5 columns]]

In [ ]:
top_peliculas.to_csv('top_peliculas_1998.csv', index=False)

In [ ]:
datos = pd.read_csv('/content/top_peliculas_1998.csv')
datos.head()

,Film,Release year,Director,Production companies,Rank
0,Citizen Kane,1941,Orson Welles,RKO Radio Pictures,1
1,Casablanca,1942,Michael Curtiz,Warner Bros. Pictures,2
2,The Godfather,1972,Francis Ford Coppola,"Paramount Pictures, Alfran Productions",3
3,Gone with the Wind,1939,Victor Fleming,Selznick International Pictures,4
4,Lawrence of Arabia,1962,David Lean,Horizon Pictures,5

###**Leyendo escribiendo archivos XML**

In [1]:
import pandas as pd

In [3]:
datos_imdb = pd.read_xml('/content/imdb_top_1000.xml')
datos_imdb.head(5)

,index,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [4]:
datos_imdb.to_xml('peliculas_imdb.xml', index=False)

###**Leyendo Banco de datos**
Creando un banco de datos local

In [9]:
import sqlalchemy

In [10]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [11]:
engine = create_engine('sqlite:///:memory:')

In [12]:
import pandas as pd

In [13]:
archivo = '/content/clientes_banco.csv'

In [14]:
datos = pd.read_csv(archivo)

In [42]:
datos.head()

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio

In [17]:
datos.to_sql('clientes', engine, index=False)

438463

In [43]:
inspector = inspect(engine)

In [26]:
print(inspector.get_table_names())

['clientes']

####**Leyendo una consulta SQL**

In [44]:
query = 'select * from clientes where Categoria_de_renta = "Empleado"'

In [45]:
empleados = pd.read_sql(query, engine)

In [48]:
empleados

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
3,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,6153651,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226053,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226054,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226056,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226057,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [ ]:
empleados.to_sql('empleados', engine, index=False)

In [ ]:
inspector = inspect(engine)
print(inspector.get_table_names())

In [ ]:
pd.read_sql_table('empleados', engine)

In [ ]:
pd.read_sql_table('empleados', engine, columns=['ID_Cliente', 'Grado_estudio','Rendimiento_anual'])

In [ ]:
query = 'select * from clientes'

In [ ]:
pd.read_sql_query(query, engine)

##**Borrando Registros**

In [36]:
from sqlalchemy.exc import SQLAlchemyError
delete = "delete from clientes where ID_Cliente = 5008804"
try:
  r_set = engine.connect().execute(text(delete))
except SQLAlchemyError as e:
  #error = str(e.__dict__['orig'])
  print(e)
else:
  print("#Registros Borrados", r_set.rowcount)

#Registros Borrados 1

In [37]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

###**Update Registro**

In [38]:
update = "update clientes set Grado_estudio = 'Nivel superior' where ID_Cliente = 5008808"
try:
  r_set = engine.connect().execute(text(update))
except SQLAlchemyError as e:
  #error = str(e.__dict__['orig'])
  print(e)
else:
  print("#Registros Updated", r_set.rowcount)

#Registros Updated 1

In [39]:
pd.read_sql_table('clientes', engine)

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008808,52,Nivel superior,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [41]:
inspector = inspect(engine)
print(inspector.get_table_names())

['clientes', 'empleados']